### ISSUE TITLE
Using images on S3

### ISSUE THREAD

**Issue by hakikihacioglu** [thaiphan/magento2-s3#4]
HI,

I installed your extension, and my media files are now also on the s3. It works real good but Magento still uses the local files. How do I make my  installation use the images on the S3?

**Comment by hakikihacioglu** [comment]
Just write your publics buckets https://s3-eu-west-1.amazonaws.com/bucketName/

Stores->Configuration->General->Web->Base URL for User Media Files

**Comment by thaiphan** [comment]
Hey @hakikihacioglu,

It looks like you've come up with a way to load images from S3 on your Magento 2 site. However, I recommend using CloudFront as there are benefits to using CloudFront over S3 in this case.

In your web server configuration, I would also recommend updating it so that all media requests are passed to get.php. The .htaccess.sample and nginx.sample files do this already.

I'm closing this ticket but feel free to open a new one if you have any other problems.

Regards,

Thai
