### ISSUE TITLE
Logo and Favicon not working

### ISSUE THREAD

**Issue by rissc** [thaiphan/magento2-s3#52]
Logo and Favicon not uploaded to S3

**Comment by thaiphan** [comment]
Where are they located on the media folder?

**Comment by bhouillon** [comment]
Hello,

I have the same problem.
Logos and Favicon are located in media folder root in folder "logo"

**Comment by vishalsanwar** [comment]
Hello

it shows me https://s3.eu-central-1.amazonaws.com/bucket-name/logo/default/logo_new.png and previously it was:
http://xyz.com/pub/media/logo/default/logo_new.png

Even other images is also not showing.

**Comment by JohnMTrimbleIII** [comment]
I have this problem too.

**Comment by thaiphan** [comment]
Hi @rissc, @bhouillon, @krishnavardhan78, @vishalsanwar, @JohnMTrimbleIII 

Thank you all for your patience.

I have published [v2.1.0](https://github.com/thaiphan/magento2-s3/releases/tag/2.1.0) of this extension so that we can now upload logos and favicons to S3.

**Warning:** I introduced a breaking change as part of [v2.0.0](https://github.com/thaiphan/magento2-s3/releases/tag/2.0.0) so you will need to re-set your `Access Key ID` and `Secret Access Key` config settings:

    php bin/magento s3:config:set \
        --access-key-id=XXXXXXX \
        --secret-key=XXXXXXX

Feel free to open up a new ticket if you come across any problems.

Regards,

Thai
